### PR TITLE
Trellinome updated for 128

### PR DESCRIPTION
**Pull request by okyeron**
Updated Trellinome for 128 button grids and fixed varibright -> monobright conversion

### CODE REVIEW

**Comment by okyeron** [comment]
OK - I have no idea what I'm doing here.  I wanted to just send a pull for the Trellinome.ino file. 

Please ignore all the other changes

**Comment by szymonkaliski** [comment]
Hey this is looking great, thanks for submitting! I'll look it over in some days and merge if all is ok on my 8x8 :)

**Comment by okyeron** [comment]
FWIW - check the addresses as I think I have them set to go 4 boards wide at first (for the 128 layout)

**Comment by szymonkaliski** [comment]
I think the projects are so far off each other that it doesn't make any sense to merge this :) Feel free to reopen if you disagree!

**Comment by okyeron** [comment]
No need to reopen. :)

**Pull request closed without merging**
